server:
  port: 8755

management:
  server:
      port: 8756
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true
eureka:
  client:
    service-url:
      DefaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: AdminServer