
server:
  port: 5711

eureka:
  client:
    service-url:
      DefaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: StatusDataService

mybatis:
  type-aliases-package: top.kribug.statusdataservice.entity
