server:
  port: 5689

mybatis:
  type-aliases-package: top.kribug.deviceservice.entity
eureka:
  client:
    service-url:
      DefaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: DeviceService
  redis:
    host: 112.74.34.69
    password:
    timeout: 60s
    lettuce:
      pool:
        max-active: -1  #最大连接数，负值表示没有限制，默认8
        max-wait: 5000    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 30     #最大空闲连接，默认8
        min-idle: 10     #最小空闲连接，默认0



  datasource:
    type: com.zaxxer.hikari.HikariDataSource


ribbon:
  eureka:
    enabled: true
