eureka:
  client:
    service-url:
      DefaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
